- name: Extract all tar.gz files (handle Replit export)
  run: |
    for f in *.tar.gz; do
      if [ -f "$f" ]; then
        echo "Extracting $f..."
        # Try normal extract, if it fails then try two-step
        tar --dereference -xvzf "$f" || (gzip -d "$f" && tar -xvf "${f%.gz}")
      fi
    donep
