name: Extract all tar.gz

on:
  push:
    branches:
      - main

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0   # puri history laane ke liye

      - name: List tar.gz files
        run: ls -lh *.tar.gz || echo "No tar.gz files found"

      - name: Extract all tar.gz files
        run: |
          for f in *.tar.gz; do
            if [ -f "$f" ]; then
              echo "Extracting $f..."
              tar -xvzf "$f"
            fi
          done

      - name: Show extracted files
        run: ls -R

      - name: Commit and Push Extracted Files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Extracted tar.gz files [skip ci]" || echo "No changes to commit"
          git push
